### ISSUE TITLE
Need to pin importlib-metadata for incompatibilities with esmpy/esmf

### ISSUE THREAD

**Issue by peanutfun** [CLIMADA-project/climada_petals#132]
We need to pin `esmpy` (a dependency of `xesmf`) to avoid version 8.4. This version is incompatible with the latest `importlib-metadata` version and causes the current builds to fail on Python 3.10+.

The pin should be
```yaml
# env_climada.yml
dependencies:
  - esmpy<8.4.0,>=8.6
```

See https://github.com/pangeo-data/xESMF/issues/374

**Comment by peanutfun** [comment]
Pinning `esmpy<8.4.0,>=8.6` is not possible, because version specifiers always imply an AND relationship. We therefore have to do `esmpy!=8.4.*`

**Comment by emanuel-schmid** [comment]
Nice! This leaves but one problem: looks like esmpy 8.4 is the only available version for Windows 😢

**Comment by peanutfun** [comment]
According to [conda-forge](https://anaconda.org/conda-forge/esmpy), v8.6 is flagged `noarch`, so it should work for Windows 🤔

**Comment by peanutfun** [comment]
Fixed by #133

**Comment by emanuel-schmid** [comment]
Right - it _should_. But, alas:

```bash
mamba install esmpy=8.6 -c conda-forge
Could not solve for environment specs
The following packages are incompatible
└─ esmpy 8.6**  is uninstallable because there are no viable options
   ├─ esmpy 8.6.0 would require
   │  └─ esmf 8.6.0.* , which does not exist (perhaps a missing channel);
   └─ esmpy 8.6.1 would require
      └─ esmf 8.6.1.* , which does not exist (perhaps a missing channel).
```

Summary:

- 8.4 is broken and inhibits import of `climada_petals.hazard.rf_glofas` for python >= 3.10,
- 8.4 is corrupted for python >= 3.9 on Windows, #127 
- 8.4 is also the only available version from conda-forge for Windows.

bottom line: `rf_glofas` doesn't work on Windows at the moment. How should we deal with this?

**Comment by peanutfun** [comment]
Ah, the issue is `esmf`, not `esmpy` 🤦 , and the problem is known: https://github.com/conda-forge/esmf-feedstock/issues/115

Then I suggest we simply pin `importlib-metadata<8.0`, because this library actually causes the issue.

I found no time to investigate #127 yet, unfortunately.

**Comment by emanuel-schmid** [comment]
Good idea, but that doesn't solve the problem, 
Perhaps because `importlib.metadata` is taken from the standard library and not from the imported package. 🤷

**Comment by peanutfun** [comment]
Did you try that? `importlib_metadata` is a third-party package with more recent features than `importlib.metadata`. According to the [original report](https://github.com/pangeo-data/xESMF/actions/runs/9685118354/job/26725324514#step:7:237) and [our logs](https://github.com/CLIMADA-project/climada_petals/actions/runs/9807409376/job/27081119339#step:9:86), the error originates in `importlib_metadata` (NO dot!) v8.0 which is way ahead of `importlib.metadata`, see https://github.com/python/importlib_metadata?tab=readme-ov-file#compatibility.

**Comment by emanuel-schmid** [comment]
Yes I have tried: 7b7dfed and then jenkins couldn't build the environment anymore. But that was perhaps just coincidence or a typeo, as it works now 8c515a6.  🎉

**Comment by peanutfun** [comment]
I'm glad! Thanks for looking into this
